### ISSUE TITLE
Run Time Limit?

### ISSUE THREAD

**Issue by JaredDavis22** [kherud/jclingo#1]
Is there a standard way to set a timeout on a run?

I would like to ensure the runtime never exceeds x seconds.

Does the clingo option

--time-limit=<n>        : Set time limit to <n> seconds (0=no limit)

work in the api?

     String[] solverArgs = {"--single-shot", "--opt-mode=opt", "--time-limit=25"};  

or does that need to be implemented  on the java side?

If on the java side, are there any examples showing preferred usage?

**Comment by rkaminsk** [comment]
The time limit is an application option that is not available when the clingo library is used. Time limits have to be handled manually. Note that the solve handle implements a wait function that takes a duration as argument.

**Comment by rkaminsk** [comment]
If I remember correctly, you have to use asynchronous solving to use the wait function. I don't have a java example ready, but here are two python examples:
```python
>>> from clingo import Control
>>>
>>> ctl = Control(["0"])
>>> ctl.configuration.solve.models = 0
>>> ctl.add("base", [], "1 { a; b } 1.")
>>> ctl.ground([("base", [])])
>>> with ctl.solve(yield_=True, async_=True) as hnd:
...     while True:
...         hnd.resume()
...         # some computation here
...         _ = hnd.wait()
...         m = hnd.model()
...         if m is None:
...             print(hnd.get())
...             break
...         print(m)
```
and
```python
>>> from clingo import Control
>>>
>>> ctl = Control(["0"])
>>> ctl.add("base", [], "1 { a; b } 1.")
>>> ctl.ground([("base", [])])
>>> with ctl.solve(on_model=print, async_=True) as hnd:
...     # some computation here
...     hnd.wait()
...     print(hnd.get())
```

**Comment by JaredDavis22** [comment]
Thanks.

Is this a correct translation?

```
public List<ClingoAnswerSet> solve(String program, String instances, String[] arguments, boolean stats, List<String> messages, Option... options) {
        LoggerCallback logger= (WarningCode code, String message) -> messages.add(message);
        control = new Control(logger, 20, arguments);
        control.getConfiguration().set(options);
        control.add(instances + program);
        control.ground();
        long timeout;

        try (SolveHandle solveHandle = control.solve(SolveMode.ASYNC_YIELD)) {
            final double TIMEOUT = 1.0; //  seconds?
            timeout = System.currentTimeMillis() + 10000; // 10 seconds
            while ((System.currentTimeMillis() < timeout) && !done) {
                solveHandle.resume();
                boolean ready = solveHandle.wait(TIMEOUT);
                Model model = null;
                if (!ready) {
                    System.out.println("False on ready");
                } else {
                    try {
                        model = solveHandle.getModel();
                        System.out.println("model = " + model);
                    } catch (NoSuchElementException noSuchElementException) {
                        System.out.println("model = null");
                    }
                }
                if (model == null) {
                    System.out.println("null model - done");
                    break;
                }
                Symbol[] symbols = model.getSymbols();
                ModelType type = model.getType();
                long[] cost = model.getCost();
                boolean opt = model.getOptimalityProven();
                ClingoAnswerSet answer = new ClingoAnswerSet(Arrays.asList(symbols), type, cost, opt, solveHandle.getSolveResult());
                answers.add(answer);

            }
        }
        System.out.println("Solutions done=" + done + " false = timeout?");
        System.out.println("timeout = " + (System.currentTimeMillis() - timeout));
        if (stats) {
            statistics = control.getStatistics();
        }
        return answers;
     }

```

**Comment by rkaminsk** [comment]
It looks like the `!ready` part needs a  continue to not break the loop prematurely. I would also compute the timeout to be passed to the wait function instead of fixing it to one second.

@kherud It seems like a NoSuchElementException is thrown when the model is null. This will happen whenever all models have been enumerated. Would it be better to just let the function return null?

**Comment by JaredDavis22** [comment]
Thanks again for your help. I added the continue and cancel call.

I'm not following this part "and call get to obtain the result of solving in case the model is null."

I started with a callback solution. The termination steps were not clear to me.

The java program returns 20 models very quickly (< .2 seconds) with the last one having the lowest costs.

```
            String[] solverArgs = {"--single-shot", "--opt-mode=opt", "-n 0"}; // "--opt-mode=optN",
            List<ClingoAnswerSet> answers = solver.solve(program, instances, solverArgs, true, messages);
```

Then it seems to take 100+ seconds to confirm it.

The program has a large amount of solutions that have the same costs. I'm happy with just one of them. 

clingo.exe produces 31 models quickly.  Exe model #31 has the same costs as java #20.

```
clingo --opt-mode=opt --single-shot -s -n 0 wires.lp
... < .2 seconds
Optimization: 1076300 4153000 1646100 3892600
...> 100 seconds
OPTIMUM FOUND

Models       : 31
  Optimum    : yes
Optimization : 1076300 4153000 1646100 3892600
Calls        : 1
Time         : 164.739s (Solving: 164.72s 1st Model: 0.00s Unsat: 164.38s)
CPU Time     : 164.484s

Choices      : 15118139
Conflicts    : 13722422 (Analyzed: 13722421)
Restarts     : 25587    (Average: 536.30 Last: 7)
Model-Level  : 58.7
Problems     : 1        (Average Length: 0.00 Splits: 0)
Lemmas       : 13722498 (Deleted: 13613377)
  Binary     : 630      (Ratio:   0.00%)
  Ternary    : 1137     (Ratio:   0.01%)
  Conflict   : 13722421 (Average Length:   31.9 Ratio: 100.00%)
  Loop       : 77       (Average Length:    3.8 Ratio:   0.00%)
  Other      : 0        (Average Length:    0.0 Ratio:   0.00%)
Backjumps    : 13722421 (Average:  1.08 Max:  96 Sum: 14805679)
  Executed   : 13722421 (Average:  1.08 Max:  96 Sum: 14805679 Ratio: 100.00%)
  Bounded    : 0        (Average:  0.00 Max:   0 Sum:      0 Ratio:   0.00%)

Rules        : 5311     (Original: 4235)
  Choice     : 430
  Minimize   : 4
Atoms        : 3030     (Original: 2727 Auxiliary: 303)
Bodies       : 3157     (Original: 2482)
  Count      : 18       (Original: 205)
Equivalences : 4245     (Atom=Atom: 658 Body=Body: 431 Other: 3156)
Tight        : No       (SCCs: 16 Non-Hcfs: 0 Nodes: 465 Gammas: 0)
Variables    : 1779     (Eliminated:    0 Frozen:  482)
Constraints  : 5806     (Binary:  66.5% Ternary:  26.9% Other:   6.6%)


```

**Comment by JaredDavis22** [comment]
I really appreciate your help on this.

SolveResult res = solveHandle.get();

When I look at the source code for SolveHandle it does not have a get() method. 

https://github.com/kherud/jclingo/blob/master/src/main/java/org/potassco/clingo/solving/SolveHandle.java

The getSolveResult() has a comment stating it will block till a result is available. Does the .cancel() call block the block?

   /**
     * Get the result of a solve call.
     * If the search is not completed yet, the function blocks until the result is ready.
     *
     * @return the solve result
     */
    public SolveResult getSolveResult() {
        IntByReference intByReference = new IntByReference();
        Clingo.check(Clingo.INSTANCE.clingo_solve_handle_get(solveHandle, intByReference));
        return new SolveResult(intByReference.getValue());
    }

**Comment by rkaminsk** [comment]
> The getSolveResult() has a comment stating it will block till a result is available. Does the .cancel() call block the block?

Yes, it is called `getSolveResult` in the Java API. If I remember correctly cancel blocks until the solver has shutdown. The following `getSolveResult` call will then return immediately. The shutdown typically happens rather quickly. In any case, it is not possible to avoid this delay without using crude means like force killing a thread or process.

**Comment by JaredDavis22** [comment]
Wow. -t2 drops the time from > 100 to < .2. Wow.

```
Optimization: 1076300 4153000 1646100 3892600
Progression : 1076300 4153000 1646100 [3816000;3892600] (Error: 0.0200734)
Progression : 1076300 4153000 1646100 [3872600;3892600] (Error: 0.00516449)
Progression : 1076300 4153000 1646100 [3882600;3892600] (Error: 0.00257559)
Progression : 1076300 4153000 1646100 [3891600;3892600] (Error: 0.000256964)
OPTIMUM FOUND

Models       : 18
  Optimum    : yes
Optimization : 1076300 4153000 1646100 3892600
Calls        : 1
Time         : 0.183s (Solving: 0.16s 1st Model: 0.00s Unsat: 0.01s)
CPU Time     : 0.141s
Threads      : 2        (Winner: 1)

Choices      : 6457
Conflicts    : 2535     (Analyzed: 2432)
Restarts     : 18       (Average: 135.11 Last: 47)
Model-Level  : 64.8
Problems     : 107      (Average Length: 0.00 Splits: 0)
Lemmas       : 3024     (Deleted: 0)
  Binary     : 200      (Ratio:   6.61%)
  Ternary    : 437      (Ratio:  14.45%)
  Conflict   : 2432     (Average Length:   25.1 Ratio:  80.42%)
  Loop       : 93       (Average Length:    4.6 Ratio:   3.08%)
  Other      : 499      (Average Length:    3.3 Ratio:  16.50%)
  Distributed: 568      (Ratio:  22.50% Average LBD: 3.97)
  Integrated : 565      (Ratio:  99.47% Unit: 22 Average Jumps: 8.68)
Backjumps    : 2432     (Average:  2.18 Max:  94 Sum:   5303)
  Executed   : 2416     (Average:  2.14 Max:  94 Sum:   5197 Ratio:  98.00%)
  Bounded    : 16       (Average:  6.62 Max:  27 Sum:    106 Ratio:   2.00%)

Rules        : 4235
  Choice     : 430
  Minimize   : 4
Atoms        : 2727
Bodies       : 2513
  Count      : 205
Equivalences : 4477     (Atom=Atom: 658 Body=Body: 431 Other: 3388)
Tight        : No       (SCCs: 16 Non-Hcfs: 0 Nodes: 465 Gammas: 0)
Variables    : 1085     (Eliminated:    0 Frozen:  598)
Constraints  : 3253     (Binary:  53.7% Ternary:  32.7% Other:  13.6%)


```

**Comment by kherud** [comment]
> @kherud It seems like a NoSuchElementException is thrown when the model is null. This will happen whenever all models have been enumerated. Would it be better to just let the function return null?

I implemented it that way since `SolveHandle` is an iterator. Throwing `NoSuchElementException` in case `hasNext` was not checked is the standard Java way I think (maybe throwing it in `getModel` is not the right place though). Looking at the code again, I think it's weird however that `hasNext` advances the iterator instead of `next`. If I remember correctly I didn't know how to otherwise check if there is a next model. Is there?

**Comment by rkaminsk** [comment]
> > @kherud It seems like a NoSuchElementException is thrown when the model is null. This will happen whenever all models have been enumerated. Would it be better to just let the function return null?
> 
> I implemented it that way since `SolveHandle` is an iterator. Throwing `NoSuchElementException` in case `hasNext` was not checked is the standard Java way I think (maybe throwing it in `getModel` is not the right place though). Looking at the code again, I think it's weird however that `hasNext` advances the iterator instead of `next`. If I remember correctly I didn't know how to otherwise check if there is a next model. Is there a way @rkaminsk ?

I think it is a bit tricky to implement this correctly using the java iterator interface. It would involve maintaining a flag that indicates whether the next model has to be searched for in `hasNext`. Like this it can be avoided that multiple calls to `hasNext` skip over models. It cannot be avoided that a call to `hasNext` invalidates the current model because it sometimes has to advance to the next one. `getModel` should better not throw an exception.

## Pseudocode:
- set flag initially to true
- hasNext:
  - if flag:
    - advance to next model
    - set flag to false
  - return true if model is not null
- next:
  - if hasNext:
    - set flag to true
    - return model
  - throw exception

**Comment by kherud** [comment]
Thank you Roland, it is fixed now.
