### ISSUE TITLE
Compiler Flags

### ISSUE THREAD

**Issue by rkaminsk** [kherud/jclingo#3]
On linux/macos the current deploy does not configure a release build. (Option --config only works with multi config generators and the default Makefile based one is single config.) Option
```
-DCMAKE_BUILD_TYPE=release
```
should be passed. Right now gcc uses the default debug optimizations leading to very slow executable code.

On Linux I would also set the following linker options:
```
-DCMAKE_SHARED_LINKER_FLAGS="-static-libgcc -static-libstdc++"
```
This links statically against gcc libraries and increases portability.

Otherwise, your dockcross setup looks nice!

EDIT: **fixed option to configure build type**

**Comment by kherud** [comment]
Thank you! I have a naive question: Is there some easy way to disable the shared library versioning (e.g. `libclingo.so.4.0`, `libclingo.so.4`, ...)? Currently I use this command

```
mv clingo/build/bin/libclingo.so.4.0 jclingo/src/main/resources/${{ matrix.target.name }}/libclingo.so
```

to move the compiled library. On the one hand, a hard coded version isn't nice. On the other hand, on some platforms, e.g. linux x86, the versioning doesn't seem to happen at all, only `libclingo.so` is output.

Probably I could just move everything with `.so`. I'm not too familiar with symbolic links, but I assume I would have to fix the links then.

**Comment by rkaminsk** [comment]
> Thank you! I have a naive question: Is there some easy way to disable the shared library versioning (e.g. `libclingo.so.4.0`, `libclingo.so.4`, ...)? Currently I use this command
> 
> ```
> mv clingo/build/bin/libclingo.so.4.0 jclingo/src/main/resources/${{ matrix.target.name }}/libclingo.so
> ```
> 
> to move the compiled library. On the one hand, a hard coded version isn't nice. On the other hand, on some platforms, e.g. linux x86, the versioning doesn't seem to happen at all, only `libclingo.so` is output.
> 
> Probably I could just move everything with `.so`. I'm not too familiar with symbolic links, but I assume I would have to fix the links then.

Just copy the library instead of moving it:
```
cp -p clingo/build/bin/libclingo.so jclingo/src/main/resources/${{ matrix.target.name }}/libclingo.so
```
